spring.application.name=UserContextualizer

spring.ai.model.chat=google-genai
spring.ai.google.genai.project-id=gen-lang-client-0253227649
spring.ai.google.genai.api-key= ${GOOGLE_API_KEY}
spring.ai.google.genai.location=europe
#spring.ai.google.genai.chat.options.model=gemini-pro