
    create table refresh_tokens (
        expiry_date timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        user_id bigint unique,
        token varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        is_enabled boolean not null,
        is_verified boolean not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        reset_token_expiry timestamp(6),
        verification_token_expiry timestamp(6),
        email varchar(255) not null unique,
        first_name varchar(255),
        last_name varchar(255),
        password_hash varchar(255) not null,
        reset_token varchar(255),
        role varchar(255) check (role in ('GUEST','USER','ADMIN')),
        username varchar(255) not null unique,
        verification_token varchar(255),
        primary key (id)
    );

    alter table if exists refresh_tokens 
       add constraint FK1lih5y2npsf8u5o3vhdb9y0os 
       foreign key (user_id) 
       references users;
