spring.application.name=InterviewEngine
jwt.secret=${JWT_SECRET}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# PostgreSQL
spring.datasource.url=${INTERVIEW_DB_URL}
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# S3
app.s3.bucket=${CV_BUCKET_NAME}
spring.cloud.aws.s3.endpoint=${INTERVIEW_S3_URL}
spring.cloud.aws.credentials.access-key=${INTERVIEW_ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${INTERVIEW_SECRET_KEY}
spring.cloud.aws.region.static=${INTERVIEW_REGION}
spring.cloud.aws.s3.path-style-access-enabled=${PATH_STYLE_ACCESS_ENABLED}

spring.ai.model.chat=google-genai
spring.ai.google.genai.project-id=gen-lang-client-0253227649
spring.ai.google.genai.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.location=europe
spring.ai.google.genai.chat.options.model=gemini-3.1-flash-lite