spring.application.name=InterviewEngine
jwt.secret=${JWT_SECRET}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://127.0.0.1:5173}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# PostgreSQL
spring.datasource.url=${DB_LINK}
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=interview

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
spring.flyway.repair-on-migrate=true
spring.flyway.schemas=interview
spring.flyway.create-schemas=true

# S3
app.s3.bucket=jobacer-cvbucket
spring.cloud.aws.s3.endpoint=${INTERVIEW_S3_URL}
spring.cloud.aws.region.static=eu-central-1
spring.cloud.aws.s3.path-style-access-enabled=false

spring.ai.model.chat=google-genai
spring.ai.google.genai.project-id=gen-lang-client-0253227649
spring.ai.google.genai.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.location=europe
spring.ai.google.genai.chat.options.model=gemini-3.1-flash-lite