
    create table ai_metrics (
        status_code integer,
        id bigint generated by default as identity,
        timestamp timestamp(6) not null,
        user_id bigint,
        endpoint varchar(255),
        ip_address varchar(255),
        primary key (id)
    );

    create table cv_info (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        user_id bigint not null,
        content TEXT not null,
        file_name varchar(255) not null,
        primary key (id)
    );

    create table interview_messages (
        role smallint not null check (role between 0 and 1),
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        interview_id bigint not null,
        content TEXT not null,
        primary key (id)
    );

    create table interviews (
        communication_score float(53),
        overall_grade float(53),
        technical_score float(53),
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        user_id bigint not null,
        context TEXT not null,
        improvement_tips TEXT,
        name varchar(255) not null,
        status varchar(255) not null check (status in ('STARTED','IN_PROGRESS','PAUSED','COMPLETED','CANCELLED')),
        strengths TEXT,
        summary TEXT,
        weaknesses TEXT,
        primary key (id)
    );

    create table jobs (
        id bigint generated by default as identity,
        user_id bigint not null,
        description TEXT not null,
        job_name varchar(255) not null,
        primary key (id)
    );

    alter table if exists interview_messages 
       add constraint FK77piqpwp3oenvihnxpblofhj6 
       foreign key (interview_id) 
       references interviews;
